-- PostgreSQL update script for Spring Security login + admin user/authority CRUD
-- Project: /opt/tuonghoa/demo
--
-- What this script does:
-- 1) Ensures tables used by the app exist: userTB, authorities
-- 2) Adds missing columns expected by com.ams.bomcore.domain.user.User
-- 3) Adds helpful indexes/constraints for username + authority lookups
-- 4) Seeds a default admin account for first login
--
-- IMPORTANT:
-- - Review the seeded admin username/email before running in production.
-- - The backend now authenticates with BCrypt version $2B and strength 13,
--   matching the legacy portal security config.
-- - Existing BCrypt hashes in the database remain valid.
-- - If you want the seeded admin hash to be generated with the exact same
--   encoder settings, regenerate it in Java with:
--   new BCryptPasswordEncoder(BCryptVersion.$2B, 13).encode("Admin@123")
-- - Change the admin password immediately after first login.

BEGIN;

-- =========================================================
-- 1) userTB table
-- =========================================================
CREATE TABLE IF NOT EXISTS "userTB" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    "firstName" varchar(255) NOT NULL DEFAULT '',
    "lastName" varchar(255) NOT NULL DEFAULT '',
    avarta varchar(255) DEFAULT '',
    email varchar(255) NOT NULL DEFAULT '',
    "isAccountNonExpired" boolean NOT NULL DEFAULT true,
    isaccountnonlocked boolean NOT NULL DEFAULT true,
    iscredentialsnonexpired boolean NOT NULL DEFAULT true,
    "isAllowMarketing" boolean NOT NULL DEFAULT false,
    mailquota integer,
    uploadquota integer,
    "titleAndHonorific" varchar(255) DEFAULT '',
    "phoneNumber" varchar(255) DEFAULT '',
    "createdTime" timestamp DEFAULT CURRENT_TIMESTAMP,
    isenabled boolean NOT NULL DEFAULT true,
    "validationCode" varchar(255) DEFAULT '',
    leaderid integer DEFAULT 0
);

ALTER TABLE "userTB"
    ADD COLUMN IF NOT EXISTS username varchar(255),
    ADD COLUMN IF NOT EXISTS password varchar(255),
    ADD COLUMN IF NOT EXISTS "firstName" varchar(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS "lastName" varchar(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS avarta varchar(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS email varchar(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS "isAccountNonExpired" boolean DEFAULT true,
    ADD COLUMN IF NOT EXISTS isaccountnonlocked boolean DEFAULT true,
    ADD COLUMN IF NOT EXISTS iscredentialsnonexpired boolean DEFAULT true,
    ADD COLUMN IF NOT EXISTS "isAllowMarketing" boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS mailquota integer,
    ADD COLUMN IF NOT EXISTS uploadquota integer,
    ADD COLUMN IF NOT EXISTS "titleAndHonorific" varchar(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS "phoneNumber" varchar(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS "createdTime" timestamp DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS isenabled boolean DEFAULT true,
    ADD COLUMN IF NOT EXISTS "validationCode" varchar(255) DEFAULT '',
    ADD COLUMN IF NOT EXISTS leaderid integer DEFAULT 0;

UPDATE "userTB"
SET
    username = COALESCE(username, ''),
    password = COALESCE(password, ''),
    "firstName" = COALESCE("firstName", ''),
    "lastName" = COALESCE("lastName", ''),
    email = COALESCE(email, ''),
    "isAccountNonExpired" = COALESCE("isAccountNonExpired", true),
    isaccountnonlocked = COALESCE(isaccountnonlocked, true),
    iscredentialsnonexpired = COALESCE(iscredentialsnonexpired, true),
    "isAllowMarketing" = COALESCE("isAllowMarketing", false),
    isenabled = COALESCE(isenabled, true),
    "validationCode" = COALESCE("validationCode", ''),
    leaderid = COALESCE(leaderid, 0)
WHERE
    username IS NULL
    OR password IS NULL
    OR "firstName" IS NULL
    OR "lastName" IS NULL
    OR email IS NULL
    OR "isAccountNonExpired" IS NULL
    OR isaccountnonlocked IS NULL
    OR iscredentialsnonexpired IS NULL
    OR "isAllowMarketing" IS NULL
    OR isenabled IS NULL
    OR "validationCode" IS NULL
    OR leaderid IS NULL;

ALTER TABLE "userTB"
    ALTER COLUMN username SET NOT NULL,
    ALTER COLUMN password SET NOT NULL,
    ALTER COLUMN "firstName" SET NOT NULL,
    ALTER COLUMN "lastName" SET NOT NULL,
    ALTER COLUMN email SET NOT NULL,
    ALTER COLUMN "isAccountNonExpired" SET NOT NULL,
    ALTER COLUMN isaccountnonlocked SET NOT NULL,
    ALTER COLUMN iscredentialsnonexpired SET NOT NULL,
    ALTER COLUMN "isAllowMarketing" SET NOT NULL,
    ALTER COLUMN isenabled SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_usertb_username'
    ) THEN
        ALTER TABLE "userTB"
            ADD CONSTRAINT uk_usertb_username UNIQUE (username);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_usertb_username ON "userTB" (username);
CREATE INDEX IF NOT EXISTS idx_usertb_email ON "userTB" (email);

-- =========================================================
-- 1b) Last-used tenant / company columns (added for per-user context persistence)
--     assignedTenantId: admin-assigned tenant for the user
-- =========================================================
ALTER TABLE "userTB"
    ADD COLUMN IF NOT EXISTS "lastTenantId"    varchar(36) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS "lastCompanyId"   varchar(36) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS "assignedTenantId" varchar(36) DEFAULT NULL;

-- =========================================================
-- 2) authorities table
-- =========================================================
CREATE TABLE IF NOT EXISTS authorities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL,
    authority varchar(255) NOT NULL,
    description varchar(255),
    visible boolean DEFAULT true
);

ALTER TABLE authorities
    ADD COLUMN IF NOT EXISTS username varchar(255),
    ADD COLUMN IF NOT EXISTS authority varchar(255),
    ADD COLUMN IF NOT EXISTS description varchar(255),
    ADD COLUMN IF NOT EXISTS visible boolean DEFAULT true;

UPDATE authorities
SET
    username = COALESCE(username, ''),
    authority = COALESCE(authority, ''),
    visible = COALESCE(visible, true)
WHERE username IS NULL OR authority IS NULL OR visible IS NULL;

ALTER TABLE authorities
    ALTER COLUMN username SET NOT NULL,
    ALTER COLUMN authority SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_authorities_username_authority'
    ) THEN
        ALTER TABLE authorities
            ADD CONSTRAINT uk_authorities_username_authority UNIQUE (username, authority);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_authorities_username ON authorities (username);
CREATE INDEX IF NOT EXISTS idx_authorities_authority ON authorities (authority);

-- =========================================================
-- 3) Seed default admin account
--    Plain password target: Admin@123
--    Replace the hash below with one generated by BCrypt $2B strength 13
--    if you want exact parity with the legacy portal setup.
-- =========================================================
INSERT INTO "userTB" (
    username,
    password,
    "firstName",
    "lastName",
    email,
    "isAccountNonExpired",
    isaccountnonlocked,
    iscredentialsnonexpired,
    "isAllowMarketing",
    isenabled,
    "createdTime",
    "validationCode",
    leaderid
)
SELECT
    'admin',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
    'System',
    'Admin',
    'admin@example.com',
    true,
    true,
    true,
    false,
    true,
    CURRENT_TIMESTAMP,
    '',
    0
WHERE NOT EXISTS (
    SELECT 1 FROM "userTB" WHERE username = 'admin'
);

INSERT INTO authorities (username, authority, description, visible)
SELECT 'admin', 'ROLE_ADMIN', 'Administrator', true
WHERE NOT EXISTS (
    SELECT 1 FROM authorities WHERE username = 'admin' AND authority = 'ROLE_ADMIN'
);

INSERT INTO authorities (username, authority, description, visible)
SELECT 'admin', 'ROLE_USER', 'Standard user', true
WHERE NOT EXISTS (
    SELECT 1 FROM authorities WHERE username = 'admin' AND authority = 'ROLE_USER'
);

COMMIT;

-- =========================================================
-- Optional verification queries
-- =========================================================
-- SELECT id, username, email, isenabled FROM "userTB" ORDER BY id;
-- SELECT id, username, authority, description, visible FROM authorities ORDER BY id;